"""empty message

Revision ID: 71379dde264a
Revises: 5e7f3cd656b0
Create Date: 2025-07-16 18:00:41.495684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71379dde264a'
down_revision = '5e7f3cd656b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
