"""Add social media fields to associations and update field lengths

Revision ID: bb749cf46a2d
Revises: 22bbac8fb605
Create Date: 2025-07-04 21:39:44.443077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb749cf46a2d'
down_revision = '22bbac8fb605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('contact_email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.alter_column('contact_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
