"""Add event_id to ratings table

Revision ID: cb756f353cb8
Revises: 557380008453
Create Date: 2025-07-09 19:51:34.774840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb756f353cb8'
down_revision = '557380008453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Primero eliminar las valoraciones existentes ya que ahora necesitan event_id
    op.execute('DELETE FROM ratings')
    
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unique_user_association_rating', type_='unique')
        batch_op.create_foreign_key('fk_ratings_event_id', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ratings_event_id', type_='foreignkey')
        batch_op.create_unique_constraint('unique_user_association_rating', ['user_id', 'association_id'])
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
